[tool.poetry]
name = "gemini_functionregistry"
version = "0.1.0"
description = "Google Gemini Function and Parser Registry"
authors = ["Torstein Sørnes <t.soernes@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
betterpathlib = "^0.1.1"
python-dotenv = "^1.0.1"
google-generativeai = "^0.8.3"
pydantic = "^2.9.2"
aiohttp = "^3.11.14"

[tool.poetry.group.dev.dependencies]
ipython = "^8.27.0"
stackprinter = "^0.2.12"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
